coverage:
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true
