#!/bin/bash

# Configuration file for interactive tutorials using binder.
#
# This file is used by binder to run code after installing the environment necessary to
# run the Jupyter notebook tutorials in the documentation.
# See also: https://mybinder.readthedocs.io/en/latest/using/config_files.html

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

# install JupyterLab extension
jupyter labextension install @jupyterlab/latex
