"""Tests for a policy returning random unit vectors."""
import copy
import pathlib

import numpy as np
from pytest_cases import parametrize_with_cases

from probnum import randvars
from probnum.linalg.solvers import LinearSolverState, policies

case_modules = (pathlib.Path(__file__).parent / "cases").stem
cases_policies = case_modules + ".policies"
cases_states = case_modules + ".states"


@parametrize_with_cases("policy", cases=cases_policies, glob="*conjugate_gradient")
@parametrize_with_cases("state", cases=cases_states)
def test_initial_action_is_negative_gradient(
    policy: policies.ConjugateGradientPolicy, state: LinearSolverState
):
    assert state.step == 0
    state = copy.deepcopy(state)
    action = policy(state)
    np.testing.assert_allclose(action, -state.residual)


@parametrize_with_cases("policy", cases=cases_policies, glob="*conjugate_*")
@parametrize_with_cases("state", cases=cases_states, has_tag=["initial"])
def test_conjugate_actions(
    policy: policies.ConjugateGradientPolicy, state: LinearSolverState
):
    """Tests whether actions generated by the policy are A-conjugate via a naive CG
    implementation."""

    solver_state = copy.deepcopy(state)
    A = solver_state.problem.A

    for _ in range(A.shape[1]):

        # Action
        s = policy(solver_state)
        solver_state.action = s

        # Observation
        y = A @ s
        solver_state.observation = y

        # Residual
        r = solver_state.residual

        # Step size
        alpha = np.linalg.norm(r) ** 2 / np.inner(s, y)

        # Solution update
        x = solver_state.belief.x.mean
        solver_state.belief.x = randvars.Constant(x + alpha * s)

        solver_state.next_step()

    actions = np.array(solver_state.actions[:-1]).T
    innerprods_actions = actions.T @ A @ actions

    np.testing.assert_allclose(
        innerprods_actions, np.diag(np.diag(innerprods_actions)), atol=1e-7, rtol=1e7
    )

    residuals = np.array(solver_state.residuals[:-1]).T
    innerprods_residuals = residuals.T @ residuals

    np.testing.assert_allclose(
        innerprods_residuals,
        np.diag(np.diag(innerprods_residuals)),
        atol=1e-7,
        rtol=1e7,
    )
